# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1854009dede91d3fc86e60e343060789c29a76a1bfc0d96effaa5059b65107bd897ee4c2c0792abc1118e276f71791fb9c98aa60310d93feb95aefb5fe3d4f1

test:
  secret_key_base: 39ce2a444b11ebdbcf3cb772bdeceb34bfa51422927b2aa50e7edb3f583b09c040bed8d95acd60a4d7370a47756ab34cff3817da3067fad2b76b264348ad6b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
